const Joi = require("joi");

module.exports.creation = {
  body: {
    doctor: Joi.string().min(1).required(),
    firstname: Joi.string().min(1).required(),
    middlename: Joi.string().min(0).optional(),
    lastname: Joi.string().min(1).required(),
    contact: Joi.string().min(1).required(),
    email: Joi.string().email({ minDomainSegments: 2 }).required(),
    birthday: Joi.string().min(1).required(),
    age: Joi.string().min(1).required(),
    location: Joi.string().min(1).required(),
    area: Joi.string().min(1).required(),
    address: Joi.string().min(1).required(),
    gender: Joi.string().min(1).required(),
    referby: Joi.string().min(1).required(),
    reason: Joi.string().min(1).required(),
    caseid: Joi.string().min(1).required(),
    language: Joi.string().min(1).required(),
    medicalHistory: Joi.string().min(1).required(),
    procedures: Joi.string().min(1).required(),
    history: Joi.string().min(1).required(),
    Group: Joi.string().min(1).required(),
    Grouplanguage: Joi.string().min(1).required(),
    profile: Joi.string().min(1).required(),
    doctornotification: Joi.array().min(1).required(),
    patientnotification: Joi.array().min(1).required(),
    idType: Joi.string().min(1).optional(),
    idnumber: Joi.string().min(1).optional(),
    date: Joi.string().min(1).required(),
    doctorid: Joi.string().min(1).required(),
    patientid: Joi.string().min(1).required(),
    fromtime: Joi.string().min(1).required(),
    totime: Joi.string().min(1).required(),
    status: Joi.string().min(1).required(),
    meetingtime: Joi.string().min(1).optional(),
  },
};
